
---
- name: Deploy PHP Example application stack
  hosts: localhost
  become: yes

  tasks:
  - name: Pull the PHP Example image
    docker_image:
      name: problemsetters/801133-ansible
      source: pull

  - name: Create a network for the application
    docker_network:
      name: php_example_net

  - name: Start the db container
    docker_container:
      name: db
      image: mysql:5.7
      env:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: example
        MYSQL_USER: example
        MYSQL_PASSWORD: example
      networks:
        - name: php_example_net
      state: started

  - name: Start the web container
    docker_container:
      name: web
      image: problemsetters/801133-ansible
      ports:
        - "8000:80"
      networks:
        - name: php_example_net
      state: started
