---
- name: Deploy web and db containers
  hosts: localhost
  become: false
  tasks:
    - name: Deploy DB container
      docker_container:
        name: mydb
        image: postgres:latest
        state: started
        env:
          POSTGRES_PASSWORD: example
        ports:
          - "5432:5432"

    - name: Deploy Web container
      docker_container:
        name: myweb
        image: nginx:latest
        state: started
        ports:
          - "8080:80"

    - name: Wait for Web to respond
      uri:
        url: http://localhost:8080
        status_code: 200
        return_content: no
