---
- hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Ensure hackerboard user exists
      user:
        name: hackerboard

    - name: Ensure hackercompany group exists
      group:
        name: hackercompany

    - name: Add hackerboard to hackercompany group
      user:
        name: hackerboard
        groups: hackercompany
        append: yes

    - name: Set facts from environment variables
      set_fact:
        hackerboard_dir: "{{ lookup('env', 'HACKERBOARD_DIR') }}"
        access_key: "{{ lookup('env', 'HACKERBOARD_ACCESS_KEY') }}"

    - name: Create target directory if it does not exist
      file:
        path: "{{ hackerboard_dir }}"
        state: directory
        owner: hackerboard
        group: hackercompany
        mode: '0750'

    - name: Deploy credentials.ini using template
      template:
        src: credentials.ini.j2
        dest: "{{ hackerboard_dir }}/credentials.ini"
        owner: hackerboard
        group: hackercompany
        mode: '0640'
