- name: Deploy Application Stack as Docker Containers
  hosts: localhost
  become: yes
  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the application image
      docker_image:
        name: problemsetters/801133-ansible
        source: pull

    - name: Run the DB container
      docker_container:
        name: app_db
        image: problemsetters/801133-ansible
        state: started
        detach: true
        env:
          APP_MODE: db
        restart_policy: always

    - name: Run the Web container
      docker_container:
        name: app_web
        image: problemsetters/801133-ansible
        state: started
        detach: true
        published_ports:
          - "8000:8000"
        env:
          APP_MODE: web
        restart_policy: always
        links:
          - app_db
